FROM node:21.6.2-alpine3.19

WORKDIR /app

# if not mount git repo into container, then copy all files to container
# COPY ./server ./

# Install dependencies
RUN apk add --no-cache ffmpeg python3

# Install global npm packages
RUN npm install -g pm2

# Copy package.json and package-lock.json before other files
# Utilize Docker cache to save re-installing dependencies if unchanged
# have to copy package.json and package-lock.json first to avoid image build error, even git repo is mounted into container because the container only mounts the git repo after the image is built
COPY ./server/package*.json ./

# Install npm dependencies
RUN npm install

# if not mount git repo into container, then install node_modules
# RUN npm install
# RUN npm run build

EXPOSE 4000

CMD ["pm2-runtime", "start", "ecosystem.config.js"]
