FROM node:21.6.2-alpine3.19

WORKDIR /app

# if not mount git repo into container, then copy all files to container
# COPY ./server ./

RUN apt install npm -y
RUN apk add --no-cache ffmpeg
RUN apk add python3
RUN npm install pm2 -g

# fix error: Could not load the "sharp" module using the linuxmusl-x64 runtime
RUN npm install --os=linux --libc=musl --cpu=x64 sharp

RUN cd /app/server && npm install

# if not mount git repo into container, then install node_modules
# RUN npm install
# RUN npm run build

EXPOSE 4000

CMD ["pm2-runtime", "start", "ecosystem.config.js"]
