openapi: 3.0.3
info:
  title: Twitter clone Typescript 2024
  description: |-
    This is a sample server for a Twitter clone.
  termsOfService: http://swagger.io/terms/
  contact:
    email: hieple.dev.1209@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost:4000
    description: The local server
  - url: http://twitter-clone.hieple.com./api/v34
    description: The Twitter clone server
tags:
  - name: users
    description: API for users
paths:
  /users/login:
    post:
      tags:
        - users
      summary: Logs user into the system
      operationId: login
      requestBody:
        description: The user credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Logged in successfully'
                  result:
                    $ref: '#/components/schemas/SuccessAuthentication'
        '400':
          description: Invalid username/password
          content:
            application/json:
              schema:
                type: string
                example: 'Invalid username/password'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                example: 'Unauthorized'
        'default':
          description: unexpected error
          content:
            application/json:
              schema:
                type: string
                example: 'unexpected error'
  /users/me:
    get:
      tags:
        - users
      summary: Get me
      operationId: getMe
      security:
        - BearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Logged in successfully'
                  result:
                    $ref: '#/components/schemas/SuccessGetMe'
