# name: Docker Image CI

# on:
#   push:
#     branches: ['develop']
#   pull_request:
#     branches: ['develop']

# jobs:
#   # sử dụng khi docker chứa source code và cần phải build lại image để apply các thay đổi
#   build-and-push:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: .
#     steps:
#       - uses: actions/checkout@v3
#       # Tạo file .env.development từ trong docker image bằng các biến môi trường được set trong secrets của repository
#       - name: 'Create env file'
#         run: echo "${{ secrets.ENV_DEVELOPMENT }}" > .env.development
#       # Đăng nhập vào Docker Hub bằng username và password được set trong secrets của repository
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
#       # Build và push image lên Docker Hub với tag là latest
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: docker/Dockerfile.dev
#           push: true
#           tags: hoainghiahieple/twitter-clone-server:latest

#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Executing remote ssh commands using password
#         uses: appleboy/ssh-action@master
#         with:
#           # Địa chỉ IP của VPS
#           host: ${{ secrets.HOST }}
#           # Username và password để đăng nhập vào VPS
#           username: ${{ secrets.HOST_USERNAME }}
#           password: ${{ secrets.HOST_PASSWORD }}
#           # Không khai báo port thì mặc định sẽ là 22
#           port: ${{ secrets.PORT }}

#       - name: Pull latest code and update .env.development on VPS
#         run: |
#           docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
#           docker pull hoainghiahieple/twitter-clone-server:latest
#           sudo rm -rf Twitter-clone
#           docker run -dp 4000:4000 --name twitter-clone-server -v ~Twitter-clone/server/uploads:/app/uploads hoainghiahieple/twitter-clone-server:latest

name: Deploy

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/${{ secrets.HOST_USERNAME }}/Twitter-clone/
            git pull origin develop
            echo '${{ secrets.ENV_DEVELOPMENT }}' > .env.development
