name: Docker Image CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: echo "${{ secrets.ENV_DEVELOPMENT }}" > .env.development
      - name: Build the Docker image
        run: docker build --progress=plain -t hoainghiahieple/twitter-clone-server:v0 .
